/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,html}'],
  corePlugins: { preflight: false },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
  theme: {
    extend: {
      colors: {
        'glass-bg': 'rgba(255, 255, 255, 0.7)',
        'glass-bg-dark': 'rgba(15, 23, 42, 0.7)',
        'inverse-surface': '#213145',
        'primary-fixed': '#d3e4ff',
        'secondary-container': '#6bff8f',
        'deep-navy': '#0B1B2D',
        'primary-fixed-dim': '#b0c8ed',
        'on-secondary-fixed-variant': '#005321',
        'on-secondary-fixed': '#002109',
        primary: '#00152c',
        'surface-container-high': '#dce9ff',
        'primary-container': '#0f2a47',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#6bff8f',
        'tertiary-fixed-dim': '#edbe8b',
        'on-secondary-container': '#007432',
        'surface-tint': '#486080',
        'on-primary-container': '#7a92b4',
        'on-primary': '#ffffff',
        background: '#f8f9ff',
        secondary: '#006e2f',
        'on-tertiary-fixed-variant': '#604018',
        'on-surface-variant': '#43474d',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4ae176',
        'surface-container': '#e5eeff',
        'inverse-primary': '#b0c8ed',
        'surface-container-low': '#eff4ff',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'tertiary-fixed': '#ffddba',
        'on-tertiary-fixed': '#2b1700',
        'border-subtle': '#E2E8F0',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        tertiary: '#221100',
        error: '#ba1a1a',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001c38',
        'on-tertiary-container': '#b2885a',
        'tertiary-container': '#3e2300',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'on-background': '#0b1c30',
        outline: '#74777e',
        'inverse-on-surface': '#eaf1ff',
        'surface-gray': '#F9FAFB',
        'outline-variant': '#c4c6ce',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#304867',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'compact-padding': '8px',
        'sidebar-expanded': '240px',
        gutter: '16px',
        'sidebar-collapsed': '64px',
        'grid-margin': '24px',
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono'],
        'data-mono': ['JetBrains Mono'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'headline-md-mobile': ['Geist'],
        'headline-sm': ['Geist'],
        'headline-md': ['Geist'],
        'display-lg': ['Geist'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
}