import { useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, LoadingBlock } from '../components/States'
import { friendlyApiError } from '../lib/api'
import { finance, type BankAccount, type BankReconciliation, type CashBook } from '../lib/finance'

export default function FinanceTreasuryPage() {
  const [banks,setBanks]=useState<BankAccount[]>([]); const [books,setBooks]=useState<CashBook[]>([]); const [recs,setRecs]=useState<BankReconciliation[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selectedBank,setSelectedBank]=useState(''); const [file,setFile]=useState<File|null>(null); const [message,setMessage]=useState<string|null>(null)
  const load=async()=>{setLoading(true);setError(null);try{const [b,c,r]=await Promise.all([finance.listBankAccounts(),finance.listCashBooks(),finance.listReconciliations()]);setBanks(b);setBooks(c);setRecs(r);if(!selectedBank&&b[0])setSelectedBank(String(b[0].id))}catch(e){setError(friendlyApiError(e,'load treasury'))}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const importStatement=async()=>{if(!file||!selectedBank)return;setError(null);setMessage(null);try{const result=await finance.importBankStatement(Number(selectedBank),file);setMessage(`Imported ${result.imported} transactions; ${result.duplicates} duplicate rows were skipped.`);setFile(null);await load()}catch(e){setError(friendlyApiError(e,'import bank statement'))}}
  return <div><PageHeader title="Finance Treasury" description="Cash books, bank accounts, statement imports and reconciliation."/>{error&&<Alert tone="error">{error}</Alert>}{message&&<Alert tone="success">{message}</Alert>}
    {loading?<LoadingBlock label="Loading treasury" rows={5}/>:<>
      <div className="summary-grid" style={{marginBottom:'var(--space-4)'}}>{[{label:'Bank Accounts',value:banks.length},{label:'Cash Books',value:books.length},{label:'Reconciliations',value:recs.length},{label:'Open Reconciliations',value:recs.filter(r=>r.status==='OPEN').length}].map(x=><div className="card" key={x.label} style={{padding:'var(--space-4)'}}><p style={{color:'var(--color-ink-muted)',fontSize:'0.8125rem',fontWeight:600,textTransform:'uppercase'}}>{x.label}</p><p style={{fontSize:'1.5rem',fontWeight:700}}>{x.value}</p></div>)}</div>
      <section className="section card"><h2 className="section__title">Bank Statement Import</h2><p style={{color:'var(--color-ink-muted)'}}>CSV columns required: <code>date, amount, type</code>. Optional: <code>reference, description</code>.</p><div style={{display:'flex',gap:'var(--space-3)',alignItems:'flex-end',flexWrap:'wrap'}}><div className="field"><label className="field__label">Bank Account</label><select className="input" value={selectedBank} onChange={e=>setSelectedBank(e.target.value)}>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} — {b.account_identifier}</option>)}</select></div><div className="field"><label className="field__label">CSV Statement</label><input className="input" type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><button className="button button--primary" disabled={!file||!selectedBank} onClick={importStatement}>Import</button></div></section>
      <section className="section card"><h2 className="section__title">Bank Accounts</h2>{!banks.length?<EmptyState title="No bank accounts" description="Configure a bank account before importing statements."/>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.85rem'}}><thead><tr>{['Bank','Account','Currency','Opening','Status'].map(h=><th key={h} style={{padding:'var(--space-2)',textAlign:'left',borderBottom:'2px solid var(--color-line)'}}>{h}</th>)}</tr></thead><tbody>{banks.map(b=><tr key={b.id}><td style={{padding:'var(--space-2)'}}>{b.bank_name}</td><td style={{padding:'var(--space-2)'}}>{b.account_name} ({b.account_identifier})</td><td style={{padding:'var(--space-2)'}}>{b.currency}</td><td style={{padding:'var(--space-2)'}}>KES {Number(b.opening_balance).toLocaleString()}</td><td style={{padding:'var(--space-2)'}}><Badge tone="success">{b.status}</Badge></td></tr>)}</tbody></table></div>}</section>
      <section className="section card"><h2 className="section__title">Reconciliation History</h2>{!recs.length?<EmptyState title="No reconciliations" description="Completed and open bank reconciliations will appear here."/>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.85rem'}}><thead><tr>{['Date','Bank Account','Statement','Book','Difference','Status'].map(h=><th key={h} style={{padding:'var(--space-2)',textAlign:'left',borderBottom:'2px solid var(--color-line)'}}>{h}</th>)}</tr></thead><tbody>{recs.map(r=><tr key={r.id}><td style={{padding:'var(--space-2)'}}>{r.statement_date}</td><td style={{padding:'var(--space-2)'}}>#{r.bank_account_id}</td><td style={{padding:'var(--space-2)'}}>KES {Number(r.statement_balance).toLocaleString()}</td><td style={{padding:'var(--space-2)'}}>KES {Number(r.book_balance).toLocaleString()}</td><td style={{padding:'var(--space-2)',fontWeight:700}}>KES {Number(r.difference).toLocaleString()}</td><td style={{padding:'var(--space-2)'}}><Badge tone={r.status==='RECONCILED'?'success':'warning'}>{r.status}</Badge></td></tr>)}</tbody></table></div>}</section>
    </>}</div>
}
