import { useCallback, useEffect, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { Alert } from '../components/Alert'
import { Badge, EmptyState, LoadingBlock } from '../components/States'
import { friendlyApiError } from '../lib/api'
import { finance, type PaymentInboxItem } from '../lib/finance'

export default function FinancePaymentInboxPage() {
  const [items,setItems]=useState<PaymentInboxItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [status,setStatus]=useState(''); const [posting,setPosting]=useState<number|null>(null)
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await finance.listPaymentInbox(status||undefined))}catch(e){setError(friendlyApiError(e,'load payment inbox'))}finally{setLoading(false)}},[status])
  useEffect(()=>{load()},[load])
  async function post(item:PaymentInboxItem){setPosting(item.id);setError(null);try{await finance.postPaymentInbox(item.id);await load()}catch(e){setError(friendlyApiError(e,'post payment'))}finally{setPosting(null)}}
  return <div><PageHeader title="Payment Inbox" description="Review decoded external payments before they enter the student ledger and General Ledger."/>{error&&<Alert tone="error">{error}</Alert>}
    <div style={{display:'flex',gap:'var(--space-2)',marginBottom:'var(--space-4)'}}><select className="input" value={status} onChange={e=>setStatus(e.target.value)} style={{maxWidth:220}}><option value="">All statuses</option><option>MATCHED</option><option>UNMATCHED</option><option>POSTED</option><option>DUPLICATE</option></select><button className="button button--secondary button--sm" onClick={load}>Refresh</button></div>
    {loading?<LoadingBlock label="Loading payment inbox" rows={5}/>:!items.length?<EmptyState title="No payment inbox items" description="External payment messages will appear here for review."/>:<section className="section card"><div style={{overflowX:'auto'}}><table style={{width:'100%',fontSize:'0.85rem',borderCollapse:'collapse'}}><thead><tr style={{borderBottom:'2px solid var(--color-line)'}}>{['Date','Reference','Student ID','Amount','Channel','Match','Status','Action'].map(h=><th key={h} style={{padding:'var(--space-2)',textAlign:h==='Amount'?'right':'left'}}>{h}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id} style={{borderBottom:'1px solid var(--color-line)'}}><td style={{padding:'var(--space-2)'}}>{new Date(item.received_at).toLocaleString()}</td><td style={{padding:'var(--space-2)',fontWeight:600}}>{item.external_reference}</td><td style={{padding:'var(--space-2)'}}>{item.student_identifier||'—'}</td><td style={{padding:'var(--space-2)',textAlign:'right',fontWeight:700}}>KES {Number(item.amount).toLocaleString()}</td><td style={{padding:'var(--space-2)'}}>{item.payment_channel||item.source}</td><td style={{padding:'var(--space-2)'}}>{item.matched_student_id?`Student #${item.matched_student_id}`:'Unmatched'}</td><td style={{padding:'var(--space-2)'}}><Badge tone={item.status==='POSTED'?'success':item.status==='MATCHED'?'warning':'danger'}>{item.status}</Badge></td><td style={{padding:'var(--space-2)'}}>{item.status==='MATCHED'?<button className="button button--primary button--sm" disabled={posting===item.id} onClick={()=>post(item)}>{posting===item.id?'Posting…':'Post payment'}</button>:item.status==='POSTED'?'Posted':'Review required'}</td></tr>)}</tbody></table></div></section>}</div>
}
